### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/Metadata;

### ISSUE THREAD

**Issue by s2yed** [mo-ah-dawood/fcm_config#10]
FATAL EXCEPTION: pool-13-thread-1
E/AndroidRuntime(18427): Process: com.jadeeer.jadeeer, PID: 18427
E/AndroidRuntime(18427): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/Metadata;
E/AndroidRuntime(18427): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.lambda$getToken$1$FlutterFirebaseMessagingPlugin(FlutterFirebaseMessagingPlugin.java:165)
E/AndroidRuntime(18427): 	at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingPlugin$CIEVVSZZupyLaxqSu4HKcRkuppw.call(Unknown Source:4)
E/AndroidRuntime(18427): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/AndroidRuntime(18427): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime(18427): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime(18427): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(18427): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.Metadata" on path: DexPathList[[zip file "/data/app/com.jadeeer.jadeeer-SWNDrR58NKAkGfScmYQO7g==/base.apk"],nativeLibraryDirectories=[/data/app/com.jadeeer.jadeeer-SWNDrR58NKAkGfScmYQO7g==/lib/arm, /data/app/com.jadeeer.jadeeer-SWNDrR58NKAkGfScmYQO7g==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
E/AndroidRuntime(18427): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/AndroidRuntime(18427): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(18427): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by s2yed** [comment]
*2.0.0-dev.11

**Comment by mo-ah-dawood** [comment]
upgrade to latest version

**Comment by s2yed** [comment]
My app is not being used  Null safety 
I can't update and use the latest version because it conflicts with some libraries
This version was working for a week and then the problem appeared


D/libGLESv2(27196): STS_GLApi : DTS, ODTC are not allowed for Package : com.jadeeer.jadeeer
I/FLTFireBGExecutor(27196): Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]
E/flutter (27196): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: Cannot add new events while doing an addStream
E/flutter (27196): #0      _BroadcastStreamController.addStream (dart:async/broadcast_stream_controller.dart:276:24)
E/flutter (27196): #1      Stream.pipe (dart:async/stream.dart:698:27)
E/flutter (27196): #2      FirebaseMessaging._onMessageController.<anonymous closure> (package:firebase_messaging/src/messaging.dart:60:21)
E/flutter (27196): #3      _runGuarded (dart:async/stream_controller.dart:773:24)
E/flutter (27196): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
E/flutter (27196): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
E/flutter (27196): #6      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter (27196): #7      LocaleNotification.init (package:fcm_config/src/locale_notifications.dart:50:51)








environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.12+4
  date_format: ^1.0.8
  auto_size_text: ^2.1.0
  google_fonts: ^1.1.0
  path_provider: ^1.6.10
  font_awesome_flutter: ^8.5.0
  awesome_dialog: ^0.1.1
  sqflite: ^1.3.0
  share_extend: ^1.1.4
  file_picker: ^1.12.0
  google_maps_flutter: ^1.2.0
  location: ^3.0.1
  #  buttons_tabbar: ^0.1.1+1
  flutter_bloc: ^6.0.1
  bloc: ^6.0.0
  searchable_dropdown: ^1.1.3
  equatable: ^1.2.3
  image_picker: ^0.6.7+1

  retrofit: ^1.3.4
  logger: ^0.8.3
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1
  json_annotation : ^3.0.1
  http_parser: ^3.1.4
  rxdart: ^0.24.1
  shimmer: ^1.1.1
  lazy_loading_list: ^1.0.0+1
  flutter_simple_rating_bar: 0.0.3
  cached_network_image: ^2.4.1
  octo_image: ^0.3.0
  google_map_location_picker: ^4.1.6
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  fcm_config:
  google_sign_in: ^4.5.6
  flutter_swipe_action_cell: ^1.3.2
  image_sequence_animator: ^1.0.10
  google_maps_webservice: ^0.0.19
  flutter_svg: ^0.19.1
  colorful_safe_area: ^0.2.1
  queen_validators: ^0.0.1+9-beta
  flutter_sheet_localization: ^2.0.1
  loading_animations: ^2.1.0
  flutter_rounded_date_picker: ^2.0.0
  intl: ^0.17.0
  carousel_slider: ^3.0.0
  flutter_rating_bar: ^4.0.0
  multiselect_dropdown:
  contained_tab_bar_view: 0.7.1
  multi_select_flutter: ^4.0.0
  maps_toolkit: ^1.1.0+2
  flutter_polyline_points:
  permission_handler:
  connectivity_widget: ^0.1.7
  map_launcher: ^2.0.0
  flutter_simple_tabbar: ^0.0.2
  popup_menu: ^1.0.5

#
dependency_overrides:
  intl: ^0.17.0





[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1110], locale ar-EG)
    • Flutter version 2.2.2 at C:\flutter
    • Framework revision d79295af24 (8 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\TEBALINK\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (4 available)
    • SM G610F (mobile) • 5203fd5afa51b33f • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by mo-ah-dawood** [comment]
the problem is in firebase_messaging it self not in the package

**Comment by s2yed** [comment]
i not use firebase_messaging
