### ISSUE TITLE
Why this plugin only provide widget?

### ISSUE THREAD

**Issue by yukitaka13-1110** [mo-ah-dawood/fcm_config#11]
I want to receive push notification in provider.

I can use the onNotification callback to receive it in the provider, but it's inconvenient to have to use the widget.

Is it possible to receive push notification directory in provider?

**Comment by mo-ah-dawood** [comment]
3.0.9
`FCMConfig.instance.listenClick(_onClick)` // to listen notification click
`FirebaseMessaging.onMessage.listen(_onNewNotify)` // to listen incomming notification
