### ISSUE TITLE
Prevent using local notification plugin to change the sound of notification

### ISSUE THREAD

**Issue by erfanjazebnikoo** [mo-ah-dawood/fcm_config#12]
There is a parameter in the `displayNotification` method to control the sound of notification. It requires the `flutter_local_notification` plugin inside our project to change it. 
It's not cool to use both plugins because we are using this plugin to facilitate the implementation and, also, it made a lot of dependency incompatibility.
Could you use a boolean param instead of this object to handle the sound of notification?

**Comment by mo-ah-dawood** [comment]
This package  main task is mixing between firebase_messaging & flutter_local_notification
so its important to use flutter_local_notification to display locale notifications
