### ISSUE TITLE
[HELP] Change web notification icon

### ISSUE THREAD

**Issue by ReniDelonzek** [mo-ah-dawood/fcm_config#13]
I didn't find anything in the documentation, and looking at the code it doesn't seem to be implemented, but I'd like to confirm this/request the feature

**Comment by mo-ah-dawood** [comment]
`displayNotificationWith( )` has property called web it takes `WebNotificationDetails` 
you can use it to display with icon 
default is `/icons/icon-192.png`

but if you need to change the incomming notification from fcm
you have to change it in service worker
see [this](https://github.com/firebase/quickstart-js/blob/b2f18e87b240868dd45ca141a328f8778b6de612/messaging/firebase-messaging-sw.js#L46-L57)

**Comment by ReniDelonzek** [comment]
I followed the code indicated, but my app icon is still not displayed in the notification, am I missing something?

```
const messaging = firebase.messaging();
messaging.setBackgroundMessageHandler(function (payload) {
    console.log('[firebase-messaging-sw.js] Received background message ', payload);
    // Customize notification here
    const notificationOptions = {
        body: payload.body,
        icon: 'icons/Icon-192.png'
    };

    return self.registration.showNotification(payload.notificationTitle,
        notificationOptions);
});
```

**Comment by ReniDelonzek** [comment]
<img width="368" alt="Captura de Tela 2021-08-22 às 12 56 41" src="https://user-images.githubusercontent.com/16869726/130362012-ecd94c78-31e4-4e48-bc22-e724947cb322.png">

**Comment by ReniDelonzek** [comment]
Found the problem, the indicated documentation is out of date, the method is now onBackgroundMessage

```
...
const messaging = firebase.messaging();
messaging.onBackgroundMessage(function (payload) {
    const notificationOptions = {
        body: payload.notification.body,
        icon: '/icons/Icon-192.png'
    };
    return self.registration.showNotification(payload.notification.title,
        notificationOptions);
});
```

That worked for me. Thanks!
