### ISSUE TITLE
[HELP] How to make the browser switch to the app tab when the notification is clicked?

### ISSUE THREAD

**Issue by ReniDelonzek** [mo-ah-dawood/fcm_config#14]
As expected, notifications only appear when the user does not have the app tab open. However, when the user clicks on the notification, the browser is expected to switch from tab to app tab, but it doesn't

**Comment by ReniDelonzek** [comment]
I managed to solve this server-side with

```
webpush: {
      fcmOptions: {
             link: 'https://chat.was.ws/#/',
      },
},
```
I'll leave that open for a possible client-side solution

**Comment by mo-ah-dawood** [comment]
try to use [this](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/notificationclick_event)

in sw file
