### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method Messaging#requestPermission on channel plugins.flutter.io/firebase_messaging)

### ISSUE THREAD

**Issue by Abouassi98** [mo-ah-dawood/fcm_config#20]
![image](https://user-images.githubusercontent.com/53384802/141004421-47bf21d7-d0a0-4335-a7db-561dc006773e.png)
![image](https://user-images.githubusercontent.com/53384802/141004490-dd42674a-357d-42f9-8986-c9da28dccbe6.png)
![image](https://user-images.githubusercontent.com/53384802/141004572-047562f2-7e92-4f32-ad15-3a65d85fefbb.png)

**Comment by mo-ah-dawood** [comment]
update to fcm_config: `^3.1.4`
