### ISSUE TITLE
MissingPluginException(No implementation found for method Messaging#requestPermission on channel plugins.flutter.io/firebase_messaging

### ISSUE THREAD

**Issue by Junama** [mo-ah-dawood/fcm_config#21]

**Comment by mo-ah-dawood** [comment]
which version

**Comment by Junama** [comment]
version: fcm_config: ^3.0.9

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FCMConfig.instance.init(
      androidChannelName: "General",
      alert: true,
      provisional: true,
      sound: true,
      appAndroidIcon: "notification_icon");
  runApp(Phoenix(child: App()));
}

**Comment by mo-ah-dawood** [comment]
Please use latest version
fcm_config: ^3.1.8
and no need to call 
await Firebase.initializeApp(); by yourself

Please read the installation guide again as there is breaking changes
and update ios target to 11 as required by firebase
