### ISSUE TITLE
I upgrade to version 3.2.2 and I have an issue

### ISSUE THREAD

**Issue by youssufhebish** [mo-ah-dawood/fcm_config#23]
I have this issue

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(INVALID_ICON, The resource  could not be found. Please make sure it has been added as a drawable resource to your Android head project., null, null)

I tried to change the icon meta data like :

<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_launcher" />

making the the ic_launcher in this destination "android/app/src/main/res/drawable" but it doesn't work too

![image](https://user-images.githubusercontent.com/58888466/146729877-23be21ae-51b9-4b46-845a-2c3cc229cc9c.png)

**Comment by mo-ah-dawood** [comment]
did you have an icon in drawable called ic_launcher
if not so this the error

If you want to use app icon dont pass icon property we will use @mipmap/ic_launcher as default

**Comment by youssufhebish** [comment]
I created a new project, didn't change the icon
I didn't add icon propery 
or
this meta line in the mainfaist
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/custom_icon" />

**Comment by mo-ah-dawood** [comment]
3.3.3

**Comment by mo-ah-dawood** [comment]
Thanks
