### ISSUE TITLE
notifications only works when the app is closed. when it's working, they don't work

### ISSUE THREAD

**Issue by Junama** [mo-ah-dawood/fcm_config#25]
await FCMConfig.instance.init(    
    defaultAndroidChannel: AndroidNotificationChannel(
      'General',
      'Fcm config',
      importance: Importance.max,
      playSound: true,
      ledColor: Colors.green,
      enableLights: true,
      sound: RawResourceAndroidNotificationSound('notification'),
      
    ),
      onBackgroundMessage:_firebaseMessagingBackgroundHandler,
      alert: true,
      sound: true,
      //provisional: true,
  );

**Comment by mo-ah-dawood** [comment]
insure that the sound exist
or remove this line
`sound: RawResourceAndroidNotificationSound('notification')`
