### ISSUE TITLE
firebase_messaging_platform_interface-3.2.0/lib/src/method_channel/utils/exception.dart:13:11: Error: Method not found: 'Error.throwWithStackTrace'.

### ISSUE THREAD

**Issue by s2yed** [mo-ah-dawood/fcm_config#27]
firebase_messaging_platform_interface-3.2.0/lib/src/method_channel/utils/exception.dart:13:11: Error: Method not found: 'Error.throwWithStackTrace'.
    Error.throwWithStackTrace(exception, stackTrace);
          ^^^^^^^^^^^^^^^^^^^
/C:/Users/TEBALINK/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging_platform_interface-3.2.0/lib/src/method_channel/utils/exception.dart:16:9: Error: Method not found: 'Error.throwWithStackTrace'.
  Error.throwWithStackTrace(
        ^^^^^^^^^^^^^^^^^^^
/C:/Users/TEBALINK/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/firebase_messaging_platform_interface-3.2.0/lib/src/method_channel/utils/exception.dart:11:7: Error: A non-null value must be returned since the return type 'Never' doesn't allow null.
Never convertPlatformException(Object exception, StackTrace stackTrace) {
      ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by mo-ah-dawood** [comment]
try fcm_config 3.3.5

**Comment by s2yed** [comment]
try fcm_config 3.3.5 


Because fcm_config >=3.3.5 depends on firebase_core >=1.13.1 which requires SDK version >=2.16.0 <3.0.0, fcm_config >=3.3.5 is forbidden.
So, because sam_card depends on fcm_config ^3.3.5, version solving failed.
pub get failed (1; So, because sam_card depends on fcm_config ^3.3.5, version solving failed.)


my app 

  sdk: ">=2.12.0 <3.0.0"

**Comment by mo-ah-dawood** [comment]
It's not in fcm config 
The newest firebase packages needs SDK 2.16
So you have to upgrade your SDK
