### ISSUE TITLE
  No Firebase App IOS

### ISSUE THREAD

**Issue by tebalink** [mo-ah-dawood/fcm_config#28]
Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:159:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:53:41)
#2      FirebaseMessaging.instance (package:firebase_messaging/src/messaging.dart:32:47)
#3      FCMConfig.messaging (package:fcm_config/src/fcm_config.dart:18:56)
#4      _SplashState.initApp (package:sam_card/screen/Splash.dart:128:41)

**Comment by tebalink** [comment]
Flutter (Channel stable, 3.0.1, on macOS 12.2 21D49 darwin-arm (Rosetta), locale en-EG)
    • Flutter version 3.0.1 at /Users/tebalink/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tebalink/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • RMX2020 (mobile)       • WKKRZSZ5JZH6J7ZS                     • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro (mobile) • 6B213EEA-4794-4EF4-A07A-122E03C7F736 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64  • macOS 12.2 21D49 darwin-arm (Rosetta)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by tebalink** [comment]
sdk: ">=2.16.0 <3.0.0"

  fcm_config: ^3.3.5

**Comment by Sultandi** [comment]
Hi, got this issue on Android platform too
Regarding to this so:
_https://stackoverflow.com/questions/72833245/calling-firebase-initializeapp-returns-unable-to-establish-connection-on-chan/72835948#72835948_

perhaps fcm_config must upgrade their fcm dependencies based:
_#  firebase_core: ^1.18.0
#  firebase_messaging: ^11.4.2_
to
  **firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4**

**Comment by mo-ah-dawood** [comment]
try `3.3.7`
