### ISSUE TITLE
 Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]

### ISSUE THREAD

**Issue by s2yed** [mo-ah-dawood/fcm_config#3]
Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]
E/flutter (28064): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: Cannot add new events while doing an addStream
E/flutter (28064): #0      _BroadcastStreamController.addStream (dart:async/broadcast_stream_controller.dart:276:24)
E/flutter (28064): #1      Stream.pipe (dart:async/stream.dart:698:27)
E/flutter (28064): #2      FirebaseMessaging._onMessageController.<anonymous closure> (package:firebase_messaging/src/messaging.dart:60:21)
E/flutter (28064): #3      _runGuarded (dart:async/stream_controller.dart:773:24)
E/flutter (28064): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
E/flutter (28064): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
E/flutter (28064): #6      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
E/flutter (28064): #7      LocaleNotification.init (package:fcm_config/src/locale_notifications.dart:50:51)
E/flutter (28064): <asynchronous suspension>
E/flutter (28064):

**Comment by mo-ah-dawood** [comment]
can you update the package first and try again
