### ISSUE TITLE
in iOS forground it create 2 notifications!

### ISSUE THREAD

**Issue by abdallah-gaber** [mo-ah-dawood/fcm_config#5]
In Android it work fine and it show the right notification in all cases with the handling of the tapping event but in iOS I have 2 issues:
- in Foreground it create 2 notifications
- in app killed mode the tapping on notification not oppening the app at all

Any help in that?

**Comment by mo-ah-dawood** [comment]
try version: 3.0.6 and tell me if that issue persists

**Comment by abdallah-gaber** [comment]
OK that's good, I will try this and tell you

**Comment by abdallah-gaber** [comment]
so the first issue solved, now it's sending one notification -creating- in foreground but still the second issue exist, I think it's not related to the library but do you have any clue what may be the issue?

**Comment by mo-ah-dawood** [comment]
can you try this
[https://github.com/FirebaseExtended/flutterfire/issues/2239#issuecomment-607062067](https://github.com/FirebaseExtended/flutterfire/issues/2239#issuecomment-607062067)

**Comment by abdallah-gaber** [comment]
No it didn't solve my problem, Thank you for your help
