### ISSUE TITLE
Add notification color when displaying notification

### ISSUE THREAD

**Issue by Reprevise** [mo-ah-dawood/fcm_config#8]
The `AndroidNotificationDetails` class has support for a `color` property which should be exposed so the developer can edit the color of the notification in the tray.

**Comment by mo-ah-dawood** [comment]
3.0.8

**Comment by Reprevise** [comment]
How does the developer change the color of the notification?

**Comment by mo-ah-dawood** [comment]
Backend can send color property color : #ff0000
as described [here](https://firebase.google.com/docs/cloud-messaging/http-server-ref)

**Comment by mo-ah-dawood** [comment]
<img width="962" alt="Screen Shot 2021-08-03 at 8 43 07 PM" src="https://user-images.githubusercontent.com/31937782/128069024-a8162024-8506-43d7-8dd5-a916b951dc12.png">

**Comment by Reprevise** [comment]
The `color` property should also be added to the `displayNotification` method.

**Comment by mo-ah-dawood** [comment]
there is  a method  called `displayNotificationWith` you can use it

**Comment by mo-ah-dawood** [comment]
`FCMConfig.instance.displayNotificationWith`
